# Generated by Django 5.2.1 on 2025-05-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="battery",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="device_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
