# Generated by Django 5.2.1 on 2025-05-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0002_sensordata_battery_sensordata_device_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceSettings",
            fields=[
                (
                    "device_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("temp_control_enabled", models.BooleanField(default=False)),
                ("temp_source", models.CharField(default="inside", max_length=10)),
                ("target_temp", models.FloatField(default=25.0)),
                ("temp_function", models.CharField(default="above", max_length=10)),
                ("humidity_control_enabled", models.BooleanField(default=False)),
                ("humidity_source", models.CharField(default="inside", max_length=10)),
                ("target_humidity", models.FloatField(default=50.0)),
                ("humidity_function", models.CharField(default="below", max_length=10)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
