# Generated by Django 5.2.1 on 2025-05-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0003_devicesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="status",
            field=models.CharField(default="online", max_length=20),
        ),
    ]
