# Generated by Django 5.2.1 on 2025-05-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0004_sensordata_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="humidity",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="temperature",
            field=models.FloatField(null=True),
        ),
    ]
