# Generated by Django 5.2.1 on 2025-05-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_sensordata_abs_humidity_sensordata_dew_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='target_humidity_max',
            field=models.FloatField(default=60.0),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='target_temp_max_celsius',
            field=models.FloatField(default=30.0),
        ),
    ]
